#!/bin/bash

(make clean > /dev/null; make) || exit 1

total=0
totalmax=0

rm -f total.txt *.out

# create a temporary workspace

# Output fail information
# Only call it inside runtest, after variables are assigned
function testfail {
  echo "*****Test Failed*****";
  echo $1
  printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
  echo
  rm .1.png .2.png .3.png
}

# Test driver
function runtest {
  prog=$1
  args=$2
  testinput=$3
  grade=$4

  totalmax=`expr $totalmax + $grade`;
  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="$prog $args $inputdescr"

  echo "======= $descr ==========="
  
  file="${args##*/}"
  filename="${file%.*}"
  
  #Run original program
  ./$prog.org $args > /dev/null
  orgerrorcode=$?
  mv ${filename}_red.png .1.png
  mv ${filename}_green.png .2.png
  mv ${filename}_blue.png .3.png

  #Run tested program
  timeout 1s ./$prog $args > /dev/null
  errorcode=$?
  
  if [ $errorcode -ne $orgerrorcode ]; then
      echo "*****Test Failed*****";
      echo Error codes do not match
      printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
      echo
      return
  else
      if [ ! -f ${filename}_red.png ]; then
        testfail "File ${filename}_red.png not exists!"
		return
      fi
	  if [ ! -f ${filename}_green.png ]; then
        testfail "File ${filename}_green.png not exists!"
		return
      fi
	  if [ ! -f ${filename}_blue.png ]; then
        testfail "File ${filename}_blue.png not exists!"
		return
      fi
  fi

  ../compare ${filename}_red.png .1.png
  if [ $? -ne 0 ]; then
      testfail "Incorrect file ${filename}_red.png!"
	  return
  fi
  ../compare ${filename}_green.png .2.png
  if [ $? -ne 0 ]; then
      testfail "Incorrect file ${filename}_green.png!"
	  return
  fi
  ../compare ${filename}_blue.png .3.png
  if [ $? -ne 0 ]; then
      testfail "Incorrect file ${filename}_blue.png!"
	  return
  fi
  
  echo Test passed...;
  printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
  total=`expr $total + $grade`;
  echo
  
  rm .1.png .2.png .3.png
}

# List of tests running
runtest channels "../images/Lenna.png" none 5
runtest channels "../images/duck.png" none 5

echo > total.out
echo >> total.out
echo   "-------------------------------------------------" >> total.out
echo   "CS240: HW 2. $USER   " >> total.out
date >> total.out
echo   "-------------------------------------------------" >> total.out
cat total.txt >> total.out >> total.out
echo   "-------------------------------------------------" >> total.out
echo   "CS240: HW 2. $USER" `date` " Total: " $total of $totalmax >> total.out
echo >> total.out

cat total.out
