#!/bin/bash

(make clean > /dev/null; make) || exit 1

total=0
totalmax=0

rm -f total.txt *.out

# create a temporary workspace

# Output fail information
# Only call it inside runtest, after variables are assigned
function testfail {
  echo "*****Test Failed*****";
  echo $1
  printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
  echo
  rm .1.png
}

# Test driver
function runtest {
  prog=$1
  args=$2
  args2=$3
  testinput=$4
  grade=$5

  totalmax=`expr $totalmax + $grade`;
  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="$prog $args $args2 $inputdescr"

  echo "======= $descr ==========="
  
  file="${args##*/}"
  filename="${file%.*}"
  
  #Run original program
  ./$prog.org $args $args2 > /dev/null
  orgerrorcode=$?
  mv ${filename}_addcols.png .1.png

  #Run tested program
  timeout 1s ./$prog $args $args2 > /dev/null
  errorcode=$?
  
  if [ $errorcode -ne $orgerrorcode ]; then
      echo "*****Test Failed*****";
      echo Error codes do not match
      printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
      echo
      return
  else
      if [ ! -f ${filename}_addcols.png ]; then
        testfail "File ${filename}_addcols.png not exists!"
		return
      fi
  fi

  ../compare ${filename}_addcols.png .1.png
  if [ $? -ne 0 ]; then
      testfail "Incorrect file ${filename}_addcols.png!"
	  return
  fi
  
  echo Test passed...;
  printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
  total=`expr $total + $grade`;
  echo
  
  rm .1.png
}

# List of tests running
runtest addcols "../images/Lenna.png" 50 none 5
runtest addcols "../images/Lenna.png" 70 none 5
runtest addcols "../images/duck.png" 20 none 5

echo > total.out
echo >> total.out
echo   "-------------------------------------------------" >> total.out
echo   "CS240: HW 2. $USER   " >> total.out
date >> total.out
echo   "-------------------------------------------------" >> total.out
cat total.txt >> total.out >> total.out
echo   "-------------------------------------------------" >> total.out
echo   "CS240: HW 2. $USER" `date` " Total: " $total of $totalmax >> total.out
echo >> total.out

cat total.out
